# Generated by Django 3.1.4 on 2021-01-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebis', '0003_auto_20210111_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytagtable',
            name='ruby',
            field=models.CharField(default='ruby', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebisusertable',
            name='is_filtering',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ebisusertable',
            name='ruby',
            field=models.CharField(default='ruby', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownertable',
            name='ruby',
            field=models.CharField(default='ruby', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ebisusertable',
            name='comment',
            field=models.CharField(blank=True, default='ruby', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='comment',
            field=models.CharField(blank=True, default='text', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownertable',
            name='comment',
            field=models.CharField(blank=True, default='com', max_length=2048),
            preserve_default=False,
        ),
    ]
