# Generated by Django 3.1.4 on 2021-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebis', '0004_auto_20210116_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebisusertable',
            name='comment',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='comment',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='ownertable',
            name='comment',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
