# Generated by Django 3.1.4 on 2021-01-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebisusertable',
            name='comment',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='comment',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='ownertable',
            name='comment',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
